### ISSUE TITLE
wizard steps 

### ISSUE THREAD

**Issue by gopal416** [forwarder/meteor-wizard#12]
I am using wizard in modal dialog when there are more number of steps we can't see all the steps in the wizard, for example if I have 10 steps I can traverse all those steps  what ever I want but the problem is if modal size can show only 4 steps   and in the 5th step I can access my code but can't see my step name in the wizard.how to slove this problem.
      or
if i want to change  wizard steps  from top to left side where i should change...

**Comment by Pagebakers** [comment]
I'm not exactly sure what you mean, but this seems to be a css issue, as the package doesn't include any styling this is fully up to you.
