### ISSUE TITLE
generation of json problem after submiting the wizard

### ISSUE THREAD

**Issue by gopal416** [forwarder/meteor-wizard#15]
I am using wizard in modal dialog
here is my schema
Schema{}
Schema.admin = new SimpleSchema({
 'firstName': {
    type: String,
    index: 1,
    label:'First Name'
 },
'middleName': {
    type: String,
    index: 1,
    label:'Middle Name'
 }
});

 Template.maintemp.helpers({
    steps: function() {
      return [{
        id: 'dc_address',
        title: 'Name',
        template: 'admins',
         formId: 'dc_adminInfo_form',
        onSubmit: function(data, wizard) {
               var params=_.extend(wizard.mergedData(), data);
		console.log(params);
}
}]
})
here is my template
<template name="admins">
{{#autoForm id="dc_adminInfo_form" doc=this.data schema=Schema.admin}}
	{{> afQuickField name="firstName" placeholder="First Name"}}
	{{> afQuickField name="middleName" placeholder="Middle Name"}}
</template>	

it is work fine when i am submit wizard first time and it display json schema in my console.
here is the problem is when i submit the wizard for second time without refreshing the webpage it displays the same json 2 times in my console,for the third time it display 3 times so on but when i refresh the page it dispaly correctly for one time.Help me by saying where I am going wrong

**Comment by Pagebakers** [comment]
I'll have to see the code you're using for the modal too, to see what's going on. A running app where I can reproduce it would be really helpful.

**Comment by gopal416** [comment]
sorry for the late reply...can you give me your mail so that I can send my code..

**Comment by Pagebakers** [comment]
You can find my contact information on my profile @ https://github.com/Pagebakers

**Comment by gopal416** [comment]
i send my App to your mail  eelco@pagebakers.nl

**Comment by gopal416** [comment]
i again send my App to your mail eelco@pagebakers.nl. 
please check....

**Comment by Pagebakers** [comment]
Sorry for my late response, do you still need help? I haven't received a new copy of your app in my email.

**Comment by bipin244** [comment]
can i see working your App code because i fetch same problem @gopal416
