### ISSUE TITLE
could example for BS3 template?

### ISSUE THREAD

**Issue by thearabbit** [forwarder/meteor-wizard#16]
I would like to use with `Bootstrap 3`.
I tried custom the example package, but can't.
Please example for  `BS3'.

**Comment by Pagebakers** [comment]
I think to example on how to customize is pretty straight forward, what exactly did you try?
Maybe I can help you out with some pointers.

**Comment by yuomtheara** [comment]
I use autoform base on BS3, so I tried custom css but don't work.

**Comment by Pagebakers** [comment]
If you use the default templates, all you need is to enable the bootstrap3 theme for autoform.

For the submit buttons add btn classes to your wizard configuration, for example:
`btn btn-default`

Then for the steps you could use the breadcrumbs perhaps, see the example code how I set this up for semantic ui.

Configuration would be something like
`
{{> wizard id="my-wizard" steps=steps stepsTemplate="customStepsTemplate" buttonClasses="btn btn-default"}}
`

**Comment by yuomtheara** [comment]
I tried add `bs3` package, and change the `buttonClasses`.
And remove `autoform semantic`, form is hidden.

**Comment by Pagebakers** [comment]
I'll need to see the code and preferably a running example to see what's going on, hard to tell this way.

**Comment by yuomtheara** [comment]
I wait for bs3 example.
