### ISSUE TITLE
how to use with AutoForm.hooks({}) like "formToDoc"?

### ISSUE THREAD

**Issue by yuomtheara** [forwarder/meteor-wizard#17]
how to use with AutoForm.hooks({}) like "formToDoc"?

**Comment by Pagebakers** [comment]
This works just like you normally would add them.

If you use custom templates use the id you give the autoForm/quickform.
Otherwise the id of the form will be the step id appended with `-form`, for example `information-form`.

Then you can do
``` javascript
AutoForm. addHooks('information-form', {
docToForm: function() {}
});
```

Good luck.

**Comment by yuomtheara** [comment]
Thanks work fine.
