### ISSUE TITLE
Support to autoform type like "insert", "update"?

### ISSUE THREAD

**Issue by thearabbit** [forwarder/meteor-wizard#18]
Support to autoform type like "insert", "update"?

**Comment by Pagebakers** [comment]
I haven't actually tried this, but I think it should work out of the box.

Have you tested this already?

**Comment by yuomtheara** [comment]
OK, I will try, so don't use `onSubmit` on wizard.

**Comment by kepler** [comment]
It would be great to have the example updated with an "update" method. I can't seem to make it work (I have a rather big schema; will try to test over the example later).

**Comment by Pagebakers** [comment]
@yuomtheara have you had any luck?

let me know how it went @kepler.

When I find some time, I will create some more examples.

**Comment by bipin244** [comment]
https://github.com/bipin244/meteor-wizard-example

**Comment by bipin244** [comment]
https://github.com/bipin244/meteor-wizard-example
sorry for truble new example now here

**Comment by Pagebakers** [comment]
@bipin244 Thanks, this is a working example?

**Comment by bipin244** [comment]
yes @Pagebakers  it's working for me

**Comment by Pagebakers** [comment]
Great, thanks for setting up the example!
