### ISSUE TITLE
Reactive multi page form 

### ISSUE THREAD

**Issue by kylepierce** [forwarder/meteor-wizard#20]
Trying to create a form that is multi pages and changes based on a few inputs. I am having issues populating the templates based on inputs. For example: form has a dropdown for "Number of campers?" It stores that value in collection after hitting next. On the 2nd page it displays [x number] of forms. Using the data on the 2nd to ask something on the 3rd and 4th page.

Currently every 'step' is being saved as a session. I was able to get the number value from this session. The only way I can get it to kind of work is to hardcode indexes into '''{{> afQuickField name="campers.0.firstName"}}''' 

This package works perfect, but I can't seem to find a way to get the forms to respond properly on multi page form.

**Comment by Pagebakers** [comment]
I haven't build any dynamic forms with the package yet, but I think it can be done by reading the data from the previous step (with `wizard.mergedData()` for example) and build your schema based on the values.

**Comment by kylepierce** [comment]
I guess my issue is how can I save each step? Should I use onSubmit or something else? Apologies I am unfamiliar with autoform and simple schema.

**Comment by Pagebakers** [comment]
The same questions was asked here https://github.com/forwarder/meteor-wizard/issues/18, I'll setup an example tomorrow.

**Comment by kylepierce** [comment]
Examples would be extremely helpful. Thank you!

**Comment by Pagebakers** [comment]
If you want to save each step, you can use onSubmit on every step, save the data in a collection, and call `wizard.next()`. Something like this:

```js
  {
      // step configuration here
      onSubmit: function(data, wizard) {
        // save your data and call wizard.next(data) on succesfully saving the data.
        wizard.next(data);
      }
    }
```

Then to show fields based on input from the previous step you could do something like this.
```js
Template.dynamicStep2.helpers({
  camperFields: function() {
    var data = this.wizard.mergedData(); // this gets all data from previous steps, you can also retrieve the data from a collection, if you're saving it manually.
    var amount = data && data.campers;
    var fields = [];
    for (var i = 0; i < amount; i++ ) {
      fields.push({
        index: i,
        name: 'campers.' + i + '.name'
      });
    }
    return fields;
  }
});
```

And in your form template do:
```html
    {{#each camperFields}}
      <div class="ui vertical segment">
        <h3 class="ui header">Camper {{index}}</h3>
        {{> afQuickField name=name}}
      </div>
    {{/each}}
```

**Comment by kylepierce** [comment]
Thank you. I was on the right track, however I am still running into the problem that onSubmit is not working because it requires the next form's input. `Error: Number of Campers is required` a question on the following step.

**Comment by Pagebakers** [comment]
It's hard to say what's going on without seeing some code.
