### ISSUE TITLE
ReferenceError: SimpleSchema is not defined

### ISSUE THREAD

**Issue by Benco1** [forwarder/meteor-wizard#21]
Added package and included following in `app/lib/wizard.js`:
```
Schema = {};

Schema.stepOne = new SimpleSchema({ ...
```
along with:
```
Items.attachSchema([
  Schema.stepOne,
  Schema.stepTwo,
  Schema.stepThree,
  Schema.stepFour,
  Schema.stepFive
]);
```
Getting following error:
```
Your app is crashing. Here's the latest log.


/Users/user/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
ReferenceError: SimpleSchema is not defined
  at app/lib/wizard.js:4:22
  at app/lib/wizard.js:95:3 ...
```

As an additional side note, because I am using FlowRouter I also tried to implement the code that binds Wizard to FlowRouter, but received a similar error that Wizard was not defined.

**Comment by Pagebakers** [comment]
Be sure to add `aldeed:simple-schema` to your project aswell.

**Comment by Benco1** [comment]
So, isn't this added as a dependency?

`meteor add forwarder:autoform-wizard`
```
Changes to your project's package version selections:
                                              
aldeed:autoform            added, version 5.0.3
aldeed:simple-schema       added, version 1.1.0
forwarder:autoform-wizard  added, version 0.6.4
momentjs:moment            added, version 2.8.4
```
Additionally, I did try adding `aldeed:simple-schema` on it's own, but didn't help. Also tried moving relevant code around to test loading order, but to no avail.

**Comment by Pagebakers** [comment]
Only autoform is a dependency, simple-schema isn't used by the wizard. 

Try putting your code in Meteor.startup(function(){}); , it shouldn't me necessary but maybe it helps. 
I can't really see what's going wrong here otherwise.

**Comment by Benco1** [comment]
Assuming packages are not the issue, what is the bare minimum code needed to get a generic wizard going so I can test what breaks it?

**Comment by Pagebakers** [comment]
Have you tried running the example on your machine? https://github.com/forwarder/meteor-wizard-example

**Comment by Benco1** [comment]
Yes, just cloned and tested the example. Works fine. Going to give it another go for my project.

**Comment by Benco1** [comment]
Yeah, so weird. Affecting deleting all my code and re-adding the package with what seems to be most basic code necessary I'm still getting:
```
Your app is crashing. Here's the latest log.


/Users/costanzab/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
ReferenceError: SimpleSchema is not defined
  at app/lib/wizard.js:5:28
  at app/lib/wizard.js:32:3
...
```

**Comment by Benco1** [comment]
Did `meteor add aldeed:simple-schema'. I was able to see my wizard template by 'manually' telling FlowRouter to find it. Then I went to setup the Wizard / FlowRouter bind and now get the error:
```
ReferenceError: Wizard is not defined
  at app/lib/router.js:45:3
```
Do I need to add another package on my own, or ... ???

**Comment by Pagebakers** [comment]
Wizard is only available on the client, so make sure to wrap it in Meteor.isClient or put it somewhere in the client folder. You can name it whatever you like, meteorhacks:flow-router makes more sense indeed.

**Comment by Pagebakers** [comment]
I moved the Iron Router and Flow Router binding into separate packages and updated the wizard package. Please see the updated docs on how to use https://github.com/forwarder/meteor-wizard#routers

I also updated the Flow Router package and example to use `meteorhacks:flow-router` instead of `flow:router`, thanks.

**Comment by Benco1** [comment]
I did get the wizard working nicely. Will checkout the FR package for my routes. Thanks for the help and prompt responses!
