### ISSUE TITLE
Validation error on custom form

### ISSUE THREAD

**Issue by ndarilek** [forwarder/meteor-wizard#23]
The below code is in Jade/Livescript but is hopefully clear. I have a multi-step wizard. The first step requires you to select a resource, while the next two let you set a start/end date for when that resource is leased. The first screen works fine, and I can select a resource. The next screen refuses to let me set a date. Any input tells me that a start date is required when I click Next. It doesn't matter whether my date is valid or present. The error is always the same. Here are my step definitions for the first two steps, the first of which works fine:

Template.newLease.helpers do

  steps: -> [
    {
      id: "select"
      title: "Select"
      schema: new SimpleSchema do
        resourceId:
          type: String
          regEx: SimpleSchema.RegEx.Id
          autoform:
            options: ->
              resources = Resources.find().fetch()
              _.map resources, (r) -> {label: r.title, value: r._id}
    }
    {
      id: "startDate"
      title: "Start date"
      template: "startDate"
      formId: "startDateForm"
      schema: new SimpleSchema do
        start:
          label: "Start time"
          type: Date
    }
    ...
  ]

And my templates:

template(name = "newLease")
  h2 New lease
  +wizard(id = "newLease" steps=steps)

template(name = "calendar")
  #calendar

template(name = "startDate")
  .row
    .col-md-6
      +autoForm(id = "startDateForm" doc=step.data schema=step.schema)
        +afQuickField(name = "start" type = "datetime")
        +wizardButtons
    .col-md-6
      +calendar

Any idea what I'm missing? Thanks for any help.

**Comment by ndarilek** [comment]
Never mind, looks like this is an Autoform issue. https://github.com/ndarilek/autoform-date

Sorry for the noise.

**Comment by Pagebakers** [comment]
Cool, glad you fixed it.
