### ISSUE TITLE
Wizard navigation not working 

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#26]
Everything is working fine but the navigation / layout I'm using bootstrap 3 template so not sure why it's not getting picked up any ideas would be great 

![screen shot 2015-08-19 at 10 20 56 pm](https://cloud.githubusercontent.com/assets/169507/9366562/d68142fe-46c0-11e5-9e77-e4687748a89e.png)

**Comment by Pagebakers** [comment]
Bootstrap3 is not supported by default. You'll have to create a custom steps template.
I have an example somewhere, just a sec.

**Comment by almogdesign** [comment]
Ok that would be great I also tried adding meteor add semantic:ui but that didn't help. In demo example you have how is that done?

**Comment by Pagebakers** [comment]
Since bootstrap doesn't have a component for this usecase, you could use breadcrumbs or maybe a nav.
Something like this. This is actually based on the semanticUI example, you can find it in the source of the demo, https://github.com/forwarder/meteor-wizard-example/tree/master/client
```html
<template name="steps_bootstrap3">
  <ul class="nav nav-pills nav-justified">
  {{#each wizard.steps}}
    <li class="{{stepClass id}}">
      {{#if wizard.route}}
        <a href="{{pathForStep id}}">{{title}}</a>
      {{else}}
        <span>{{title}}</span>
      {{/if}}
    </li>
  {{/each}}
  </ul>
</template>
```
```javascript
Template.steps_bootstrap3.helpers({
  stepClass: function(id) {
    var activeStep = this.wizard.activeStep();
    var step  = this.wizard.getStep(id);
    if (activeStep && activeStep.id === id) {
      return 'active';
    }
    if (step.data()) {
      return 'completed';
    }
    return 'disabled';
  }
});
```

```html
{{> wizard id="order" route="order" steps=steps stepsTemplate="steps_bootstrap3" buttonClasses="btn"}}
```

**Comment by almogdesign** [comment]
Thanks I got semantic UI working and the bootstrap example you just sent, breadcrumbs or nav don't look good at all. It would be nice to have the following supported https://github.com/VinceG/twitter-bootstrap-wizard 

Used it for a number of projects really good.

**Comment by thearabbit** [comment]
I would like to use with bootstrap-wizard style too.
Please example.
