### ISSUE TITLE
Question - ParselyJS or smart client side validation support 

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#27]
I noticed that only client side validation is required it would be nice to support parselyjs or smarter validation for numbers and so forth

**Comment by Pagebakers** [comment]
The inner workings of the wizard are all based around autoform (and simpleschema), which handles the validation too. If you require other validation options, you can refer to the simple schema docs at https://github.com/aldeed/meteor-simple-schema

**Comment by almogdesign** [comment]
thanks
