### ISSUE TITLE
Have you tested this on more then 2 steps 

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#28]
I see that all the steps are working but it does not show step 3 or step 4 in UI attached screenshots 
![screen shot 2015-08-19 at 11 14 40 pm](https://cloud.githubusercontent.com/assets/169507/9367781/3d9f3cbe-46c8-11e5-8bd7-cb16888de756.png)

![screen shot 2015-08-19 at 11 14 47 pm](https://cloud.githubusercontent.com/assets/169507/9367783/40bf22a6-46c8-11e5-8654-daeebf39fa35.png)

**Comment by Pagebakers** [comment]
Haven't tried this with semanticUI, it looks like a css/render issue.
Maybe the markup isn't completely correct, could you check?

**Comment by almogdesign** [comment]
Markup is like the example you have 
```html
<template name="steps_semantic_ui">
    <div class="ui two steps">
        {{#each wizard.steps}}
            <div class="{{stepClass id}} step">
                {{#if icon}}<i class="info icon"></i>{{/if}}
                <div class="content">
                    {{#if wizard.route}}
                        <a href="{{pathForStep id}}" class="title">{{title}}</a>
                    {{else}}
                        <div class="title">{{title}}</div>
                    {{/if}}
                </div>
            </div>
        {{/each}}
    </div>
</template>
```


```html
{{> wizard id="posts" steps=steps stepsTemplate="steps_semantic_ui" buttonClasses="ui button"}}
```

And I installed the following packages 
semantic:ui-css
fabienb4:autoform-semantic-ui

**Comment by Pagebakers** [comment]
Ahhhh, i see the culprit. Remove `two` from `<div class="ui two steps">`

**Comment by almogdesign** [comment]
Great thanks you can't remove it or you will not have the navigation just need to set it to forth
