### ISSUE TITLE
 ReferenceError: Wizard is not defined

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#29]
Getting the following error when adding "Wizard.useRouter('iron:router');"
 -  ReferenceError: Wizard is not defined

Here is my route
```javascript
Router.route('createPost', {
    layoutTemplate: 'layoutApp',
    path: '/create-post/:step',
    name: 'createPost',
    waitOn: function(){
        return [Meteor.subscribe('currentUser')];
    }
});
```

 {{> wizard id="posts" steps=steps route="createPost" stepsTemplate="steps_semantic_ui" buttonClasses="ui button"}}

**Comment by Pagebakers** [comment]
Where did you put `Wizard.useRouter('iron:router');` ? 

Wizard is only available on the client, so if this is run in common (client+server) code it'll throw this error.

**Comment by almogdesign** [comment]
Yea that was it might be good to add it the docs thanks appreciate it

**Comment by Pagebakers** [comment]
Great! I'll update the docs
