### ISSUE TITLE
Setting up steps without templates just simple-schema?

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#3]
Is it possible to setup steps without creating a template just simple-schema and autoform?

**Comment by Pagebakers** [comment]
I wanted to keep things flexible, so you'll need to setup templates for now. 

I like the idea though, even less configuration :)

**Comment by Pagebakers** [comment]
I made the `template` and `formId` configurations optional, all you need to do now is adding a schema.

Cheers
