### ISSUE TITLE
Can't move past step 2 

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#30]
For someone reason I can't get past step two it just reloads back to step one, is there an example with four or five steps. Maybe this is something to do with the routes. Attached gif showing the issue 

![form_wizard_issue](https://cloud.githubusercontent.com/assets/169507/9369439/b7180996-46d1-11e5-81f1-009fbbe6be8d.gif)

**Comment by almogdesign** [comment]
Now the routes are working I can manually navigate to the app via URL if doing "http://localhost:3000/create-post/postsStep4" 

but with the next still not working

**Comment by almogdesign** [comment]
I'm thinking it has something to do with the URL any idea what might be causing this 

![screen shot 2015-08-20 at 2 19 24 am](https://cloud.githubusercontent.com/assets/169507/9371967/f89b9288-46e1-11e5-9327-105545ff5455.png)

**Comment by Pagebakers** [comment]
Can I see your steps definition code?

Most likely it's one of the following problems:
1. It could be there's an onSubmit handler in step2 that isn't setup correctly
2. An error is thrown on step2.

**Comment by almogdesign** [comment]
Yes that is what I thought but I'm not getting any errors here is my steps definition 
```javascript
Template.createPost.helpers({
    steps: function() {
        return [
            {
                id: 'post-step-1',
                title: 'Step 1',
                schema: Schemas.postStep1
            },
            {
                id: 'postStep2',
                title: 'Step 2',
                schema: Schemas.postStep2
            },
            {
                id: 'postStep3',
                title: 'Step 3',
                schema: Schemas.postStep3
            },
            {
                id: 'postStep4',
                title: 'Step 4',
                schema: Schemas.postStep4
            }/*,
            {
                id: 'confirm',
                title: 'Confirm',
                schema: Schemas.postsUse,
                onSubmit: function(data, wizard) {
                    // submit logic
                }
            }*/]
    }
});
```

**Comment by Pagebakers** [comment]
Thanks, that's weird, though it looks like your page is refreshed. Can you enable Preserve log in your console? So we can be sure you don't get any errors.

**Comment by almogdesign** [comment]
Yes I'm getting the following error with preserve log, which I forgot about 

Uncaught TypeError: Cannot read property 'apply' of undefined(anonymous function) @ 002_jquery-ui.js?3263b98139357411b9f09f373940ee92f4fb6e7b:10049n.extend.each @ 001_jquery-2.1.4.min.js?43dc554608df885a59ddeece1598c6ace434d747:2n.fn.n.each @ 001_jquery-2.1.4.min.js?43dc554608df885a59ddeece1598c6ace434d747:2$.fn.datepicker @ 002_jquery-ui.js?3263b98139357411b9f09f373940ee92f4fb6e7b:10046AutoForm.addInputType.valueOut @ autoform-bs-datepicker.js:7autoFormGetInputValue @ autoform-api.js:514(anonymous function) @ autoform-inputs.js:6jQuery.extend.each @ jquery.js:384jQuery.fn.jQuery.each @ jquery.js:136getFlatDocOfFieldValues @ autoform-inputs.js:5autoFormGetFormValues @ autoform-api.js:311autoFormSubmitHandler @ autoform-events.js:158(anonymous function) @ template.js:463Template._withTemplateInstanceFunc @ template.js:437(anonymous function) @ template.js:462(anonymous function) @ view.js:869Blaze._withCurrentView @ view.js:523(anonymous function) @ view.js:868(anonymous function) @ events.js:47jQuery.event.dispatch @ jquery.js:4665elemData.handle @ jquery.js:4333
Navigated to http://localhost:3000/create-post/postStep2?unitsTotal=&unitOfMeasure=2013&use=e&bestUsedBy=08%2F24%2F2015&mustUseBy=08%2F24%2F2015&idealUse=e
ga.js:30 iron-router-ga settings not found

**Comment by Pagebakers** [comment]
Which datepicker plugin are you using?

**Comment by almogdesign** [comment]
https://atmospherejs.com/aldeed/autoform-bs-datepicker

**Comment by almogdesign** [comment]
@Pagebakers I tried to debug this a bit and it looks the wizard is not supporting the date picker are you getting the same on your end?

**Comment by Pagebakers** [comment]
There were more people having issues, i couldn't reproduce though. see https://github.com/forwarder/meteor-wizard/issues/4

Can you put a demo online?

**Comment by almogdesign** [comment]
I don't think it's a validation issue at least what I'm getting. It's definitely an issue with the date picker package. I'm not sure why you can't reproduce it I just tested it again if I comment out the autoform it works great. So all you need to do is install it on your demo example and you will run into the same issue. 
```javascript
bestUsedBy: {
        type: Date,
        label: "Best Used By"//,
        /*autoform: {
            type: "bootstrap-datepicker"
        }*/
    }, 
```

If your not running into the issue then it's has something to do with jquery UI which I have directly in my compatibility folder. But let me know I can further test?

**Comment by Pagebakers** [comment]
Yes, can you try to remove jquery.ui?

**Comment by almogdesign** [comment]
Ok it's not jquery or jquery UI its the date picker package I guess the wizard does not support it 
The error that I get 
Uncaught TypeError: this.datepicker is not a function

**Comment by Pagebakers** [comment]
Ok, last thing I need to know. 

Try creating a regular autoform outside of the wizard, then see if you still get the same result.
If not I will have a deeper look into this.

**Comment by almogdesign** [comment]
Just did, still getting the error so it's not the wizard let me move to the plugin site
