### ISSUE TITLE
Support select2 custom options 

### ISSUE THREAD

**Issue by almogdesign** [forwarder/meteor-wizard#31]
I'm using the autoform select2 package - https://atmospherejs.com/aldeed/autoform-select2
It would be nice to have a way to pass in custom options like so 

Template.example.helpers({
  s2Opts: function () {
    return {placeholder: 'foo', tags: true};
  }
});

which is added to the 
 {{> afFieldInput name="tags" type="select2" multiple=true select2Options=s2Opts}}

I guess you would need a way to set this per select2 field

**Comment by Pagebakers** [comment]
Sure that's no problem, there are a couple of ways to do this. 

Normally the data context of the template which contains the wizard should be accessible in the forms.

Another solution would be to create custom templates for you steps and add the helpers here.

If this doesn't work you can access data of the parent template with `{{../../s2Opts}}` (the dept depends on your template structure)

**Comment by almogdesign** [comment]
Can you explain this a bit not sure I understood this "Normally the data context of the template which contains the wizard should be accessible in the forms."

**Comment by almogdesign** [comment]
If you have an example that would be great I can later do a PR request updating the docs if you like

**Comment by Pagebakers** [comment]
What solution did you use in the end?

**Comment by almogdesign** [comment]
Just pure HTML using bootstrap 3 and for the wizard I used jquery.bootstrap.wizard.js
