### ISSUE TITLE
Expose WizardConstructor for add custom methods

### ISSUE THREAD

**Issue by bySabi** [forwarder/meteor-wizard#36]
If WizardConstructor object was expose is posible to add custom methods.

Maybe, `Wizard.WizardConstructor` 

Right know I just using `Wizard.extendOptions` from proposed PR https://github.com/forwarder/meteor-wizard/pull/38 for extend WizardConstructor but exposed object constructor is more appropiate.

Edit: Created new PR https://github.com/forwarder/meteor-wizard/pull/38

**Comment by Pagebakers** [comment]
Let's continue this discussion in the PR, thanks!
