### ISSUE TITLE
Doesn't work with datepicker (aldeed:autoform-bs-datepicker)

### ISSUE THREAD

**Issue by coniel** [forwarder/meteor-wizard#4]
I'm using aldeed:autoform-bs-datepicker and I've added a couple of datepickers to my wizard, but they fail to validate: "Start date must be a Date". I'm guessing that the wizard is reading the string shown in the text input rather than the date object.

**Comment by Pagebakers** [comment]
You still have this problem? the wizard doesn't override any validation, so I'm not sure why this fails.
Do you have an example online?

**Comment by yuomtheara** [comment]
You can try config `datepicker` on template render (not schema).

**Comment by Pagebakers** [comment]
Released a new version 0.6.1 that uses AutoForm 5+. I tested Aldeed's datepicker plugin and the validation works fine with these versions.
