### ISSUE TITLE
problem on Back button

### ISSUE THREAD

**Issue by gopal416** [forwarder/meteor-wizard#44]
here i am using back button in my wizard.
    here is the code  
     Template.TemplateName.events({
                          'click .back': function(e, template) {
                           e.preventDefault();
                           this.wizard.previous();
  }
});
 it works fine. 
 but i want to move back to particular wizardStep 
   here the code  i used :
    Template.TemplateName.events({
                          'click .back': function(e, template) {
                           e.preventDefault();
                           this.wizard.previous("PreviousTemplateName");
  }
});
 It's not moving back to desired step and also some times stuck the entire wizard.
Please show me solution for my problem

**Comment by bySabi** [comment]
Replace:
  `this.wizard.previous("PreviousTemplateName")`
with:
 `this.wizard.previous("StepIdName")` the step.id you passed on `steps` helper
