### ISSUE TITLE
Some examples on autoform-wizard-flow-router?

### ISSUE THREAD

**Issue by Viking-yu** [forwarder/meteor-wizard#45]
I'm new at Meteor. I tested your package (http://autoform-wizard.meteor.com). It worked great with iron-router! But flow-router is used in my app instead. I tried to modify your example to work with forwarder:autoform-wizard-flow-router, but failed. Would you like to show this example? Thank you very much!

**Comment by bySabi** [comment]
Is a FlowRouter example here: 
      http://autoform-wizard-flowrouter-bootstrap.meteor.com/

and the repo here: 
     https://github.com/bySabi/meteor-wizard-example-with-flowrouter-bootstrap
