### ISSUE TITLE
Breaks if there are other params in iron router

### ISSUE THREAD

**Issue by Neobii** [forwarder/meteor-wizard#5]
This little bit of code will throw out any other params previously in the url.

```javascript
    if(this.route) {
      Router.go(this.route, {step: id});
    } else {
      this.setStep(id);
    }
```
https://github.com/forwarder/meteor-wizard/blob/master/wizard.js#L179

**Comment by Neobii** [comment]
I fixed it here, https://github.com/LearnEverything/meteor-wizard, but I cloned from a different fork.

**Comment by Pagebakers** [comment]
Thanks! I updated the package to keep existing route parameters.
