### ISSUE TITLE
adding wizardClasses to the options

### ISSUE THREAD

**Issue by Findegil** [forwarder/meteor-wizard#53]
Today I wanted to style the wizard via semantic-ui grid.  For the purpose I needed to pass the classes "ui grid" to the wizard, (not willing to copy the entire css and pass it to .wizard). I decided i will edit the package.

I added ```  'wizardClasses'``` to the _the options in wizard.js 
and edited the line in the html file like so:
  ```handlebars
<div id="{{wizard.id}}" class="wizard {{wizardClasses}}"> 
````

wizard class gets passed to the wizard, and any other static classes but its not passing any dynamic if i call it  like so 
```handlebars
 {{> wizard id="basic-wizard" steps=steps wizardClasses="grid ui"}}
```
What am I missing?

**Comment by bySabi** [comment]
You can add  a options this way:
`Wizard.extendOptions(['wizardClasses'])`
or with defaults value:
`Wizard.extendOptions(['wizardClasses'], {wizardClasses: 'grid ui'})`

This must be on docs, sorry for that :-(


Test with this: 
`<div id="{{wizard.id}}" class="wizard {{wizard.wizardClasses}}"> `
