### ISSUE TITLE
Question:  Howto add "Login" step.  Skip step forward/backward if already logged in?

### ISSUE THREAD

**Issue by MichaelJCole** [forwarder/meteor-wizard#58]
Hi :-)

How can I skip a step if it's not appropriate.  I have this form progression:

PromiseStuff -> Login -> Verification -> Confirmation -> DeliverStuff

I want to skip Login and/or Verification steps if the user is logged in and/or verified.

PromiseStuff.next() -> Confirmation
Confirmation.prev() -> PromiseStuff

I didn't [see a way to do this](https://github.com/forwarder/meteor-wizard/blob/master/wizard.js#L178), but maybe I missed something? 

Optimally, it would be nice to pass a configuration option `skipIf` a boolean function to tell the form logic to keep going forward/backwards.

Any suggestions?

Thanks!

**Comment by Pagebakers** [comment]
You probably found a solution by now, but there are a couple of ways to do it.

Probably the best way would be to make the step config dynamic based on the logged in status of the user.

Other ways to do would be to check if the user is logged in on the onSubmit handler of PromiseStuff and instead of using `next()` use `show(id)` to skip the login.

I like the idea of having a `skipIf` handler, or perhaps having a onBeforeShow hook where you can handle this logic.

**Comment by MichaelJCole** [comment]
Hey, thanks for the comment.  I rolled my own.  The most important thing I learned was to make a `next(currentPage, direction)` function.  That let the forward backword logic be as complex as it needed.

Thanks!

**Comment by Pagebakers** [comment]
Cool, could you elaborate a bit more on that? I think this'll be a useful for more people and I'm happy to update the package to support this.

**Comment by MichaelJCole** [comment]
Hey, sure.  So I implemented this in javascript, by showing hiding divs.  Below is the code I used.  It could be refactored to use data structures instead of skipStep(), but hope it's helpful :-)

Imagine form helpers: 
```
Template.connectFormAccount.events({
  'click .step-button-prev': function(e, template) {
    template.error.set(false);
    Helpers.connectForm.setStep('account', 'prev'); // On account.  Goto previous.
  },  'click .step-button-next': function(e, template) {
    template.error.set(false);
    Helpers.connectForm.setStep('account', 'next'); // On account.  Goto next.
  },
```

Here's how setStep was implemented:
```
Helpers = {}
Helpers.connectForm = {
  setStep: function(currentStep, direction) {
    var nextStep = currentStep || 'start';
    if (direction) nextStep = Helpers.connectForm.calculateStep(currentStep, direction);
    Helpers.connectForm.showStep(nextStep);
  },

  // What's our next step?
  calculateStep: function (currentStep, direction) {
    var newStep = Helpers.connectForm.progressStep(currentStep, direction);
    newStep = Helpers.connectForm.skipSteps(newStep, direction);
    return newStep;
  },
  // Keep skipping till done.
  skipSteps: function(currentStep, direction) {
    var newStep = currentStep;
    while (Helpers.connectForm.skipStep(newStep)) {
      newStep = Helpers.connectForm.progressStep(newStep, direction);
    }
    return newStep;
  },
  // should we skip this one step?
  skipStep: function(currentStep) {
    if (currentStep === 'account' && Meteor.userId()) return true;
    if (currentStep === 'verify' && Meteor.user() &&
      Meteor.user().checkSignUpReputation())
        return true;
    return false;
  },
  // The form progression
  progressStep: function(currentStep, direction) {
    if (!currentStep || !direction) throw new Meteor.Error('invalid step or direction');
    var steps = ['when', 'what', 'account', 'verify', 'browser', 'payment', 'waiting'];
    var i = steps.indexOf(currentStep) + (direction==='next' ? 1 : -1);
    if (i < 0 || i > steps.length) throw new Meteor.Error('Invalid step:'+i);
    return steps[i];
  },
};
```
