### ISSUE TITLE
Can I use the same template for different forms?

### ISSUE THREAD

**Issue by TheSp00k** [forwarder/meteor-wizard#60]
Hello, 
I am creating a quiz that only contains question + answer forms. Basically all forms could be in the same template, but defined differently in schemas. I don't want to define the same template with different ids. I have made this setup, but after submitting the first form the next button gets disabled. As I figured out, it is a double submit prevention. It is triggered after pressing the submit button, but it is not changed back to normal before loading next question. Is there a quick solution to this problem? I would like to know your opinion on this one.
There is my example. 
The form template name is the same for all forms, but form ids and schemas are different:

    <template name="test">
    {{console.log this}}
    {{#autoForm schema=this.step.schema id=this.step.formId}}
    <div class="headline">
        <h2>{{this.step.title}}</h2>
    </div>
    <fieldset>
        {{> afQuickField name='answers'}}
    </fieldset>
    <button type="submit" class="btn btn-success btn-lg pull-right">Next</button>
    {{/autoForm}}
</template>

The steps definition:

     return [
            {
                id: 'question1',
                formId: 'question1',
                title: 'test1',
                template: 'test',
                schema: Schema.pointsUser.question1
            },
            {
                id: 'question2',
                formId: 'question2',
                template: 'test',
                title: 'test2',
                schema: Schema.pointsUser.question2
            },
            {
                id: 'question3',
                formId: 'question3',
                template: 'test',
                title: 'test3',
                schema: Schema.pointsUser.question3
            }
    ];

And the schemas:

    question1: new SimpleSchema({
        answers: {
            type: [String],
            autoform: {
                type: "select-checkbox",
                label: false,
                options: function () {
                    return [
                        {
                            label: "qwerty",
                            value: 1
                        },
                        {
                            label: "asdfg",
                            value: 2
                        },
                        {
                            label: "zxczxv",
                            value: 3
                        }
                    ];
                }
            }
        }
    }),
    question2: new SimpleSchema({
        answers: {
            type: String,
            autoform: {
                type: "select-radio",
                label: false,
                options: function () {
                    return [
                        {
                            label: "qwerty",
                            value: 1
                        },
                        {
                            label: "zxcvbfr",
                            value: 2
                        },
                        {
                            label: "aaaa",
                            value: 3
                        }
                    ];
                }
            }
        }
    }),
    question3: new SimpleSchema({
        answers: {
            type: String,
            autoform: {
                type: "select-radio",
                label: false,
                options: function () {
                    return [
                        {
                            label: "123",
                            value: 1
                        },
                        {
                            label: "312",
                            value: 2
                        },
                        {
                            label: "753",
                            value: 3
                        }
                    ];
                }
            }
        }
    }),

**Comment by guns2410** [comment]
+1 facing the same issue

**Comment by Pagebakers** [comment]
I think it's because this.done(); isn't called in the onSubmit handler of the wizard.

```js
    AutoForm.addHooks(step.formId, {
      onSubmit: function(data) {
        this.event.preventDefault();

        if(step.onSubmit) {
          step.onSubmit.call(this, data, self);
        } else {
          self.next(data);
          this.done(); // this needs to be added in wizard.js
        }
      }
    }, true);
```

Can you test if this works? if it does i'll publish an update

**Comment by guns2410** [comment]
@Pagebakers sorry for the delayed response. Yes, it does work! Thanks!

**Comment by Pagebakers** [comment]
Great thanks!
