### ISSUE TITLE
Validation attribute not working

### ISSUE THREAD

**Issue by xvendo** [forwarder/meteor-wizard#61]
If you set validation="blur" the elements won't get validated. They only get validated on "submit".

See the fine tuning section for more:
https://github.com/aldeed/meteor-autoform#fine-tuning-validation

**Comment by Pagebakers** [comment]
Can you post some example code?

**Comment by xvendo** [comment]
I checked It again and It works.
Thank you.

**Comment by Pagebakers** [comment]
Cool, thanks!
