### ISSUE TITLE
Example of using onSubmit hook?

### ISSUE THREAD

**Issue by brylie** [forwarder/meteor-wizard#64]
The documentation mentions using the `onSubmit` hook, but does not give a specific example. How do we use the onSubmit hook?

E.g. in AutoForm, hooks are used as such:

```js
AutoForm.hooks({
  "autoform-wizard": {
    onSubmit: function () {
      console.log("submit");
    }
  }
});
```

However, the above code does not work with an AutoForm Wizard by the same ID.

**Comment by Pagebakers** [comment]
You can find an example here, using onSubmit on the last step.
https://github.com/forwarder/meteor-wizard-example/blob/master/client/basic/basic.js#L66

You can also use the onSubmit handler on all other steps, in that case you call `wizard.next(data)` to go to the next step.
