### ISSUE TITLE
Multi step form: clicking back then next from 2nd step loses 2nd step's data

### ISSUE THREAD

**Issue by smanji** [forwarder/meteor-wizard#67]
I'm using a quick wizard with 3 steps. The 2nd and 3rd step use a custom template each defining an autoform.

When I'm on the 2nd step and I fill out the autoform then click next to the 3rd step and fill out the 3rd step's autoform, then:
1. click back: I'm on the 2nd step and all entered data is present
2. click next: I'm now on the 3rd step and all my entered data is cleared!
3. click back: I'm now on the 2nd step and my entered data is present
4. click back: I'm now on the 1st step and my entered data is present
5. click next: I'm ow on the 2nd step and my entered data is cleared!

Why does moving forward through the wizard (by clicking next) seem to clear that next step if data was entered?

I've checked the this.data.wizard.mergedData() and it is also losing the data...

Is this the expected behaviour? Is there a bug? Or might I be doing something wrong?

**Comment by samuelluis** [comment]
https://github.com/forwarder/meteor-wizard/pull/68/files

**Comment by Pagebakers** [comment]
This was by design initially, since you data is only saved upon submission, going back doesn't submit the current form. Though i agree it should be expected to store the current values upon navigating the wizard. Let's discuss this further in #68
