### ISSUE TITLE
I cant get to step 2? Is an Auto form required on each step to proceed to the next?

### ISSUE THREAD

**Issue by faceyspacey** [forwarder/meteor-wizard#7]
I'm using ````wizard.next()````, and going to the url of the next step directly. In both cases it redirects back to the first step. How can I override it? Anyway without autoform? Maybe use your ````setData()```` method??

**Comment by Pagebakers** [comment]
A form is required on each step. What are you trying to accomplish?

**Comment by Pagebakers** [comment]
There's no way to create steps without Autoform, since the wizard relies on the onSubmit handler of Autoform. 

What you can do is create a schema with a single field that has a defaultValue or is optional. Add this as a hidden field in the form.
