### ISSUE TITLE
Can't get updated value of "wizard.mergedData()" for previous step when submit update form.

### ISSUE THREAD

**Issue by thearabbit** [forwarder/meteor-wizard#71]
I create update form
```js
// Template
{{> wizard id="product" steps=steps stepsTemplate="steps_bootstrap3" clearOnDestroy=true}}

<template name="productGeneralStep">
    {{#autoForm id="productGeneralStep" schema=step.schema doc=step.data}}
     .........
<template name="productLaonAmountStep">
    {{#autoForm id="productLaonAmountStep" schema=step.schema doc=step.data}}
    .........

// JS
insertTpl.helpers({
    steps: function () {
       // Set initial data to update
        var initialData = Loan.Collection.Product.findOne(this._id);

        return [
            {
                id: 'general',
                title: 'General',
                template: 'productGeneralStep',
                formId: 'productGeneralStep',
                schema: Schema.Product.general,
                data: initialData
            },
            {
                id: 'loanAmount',
                title: 'Loan Amount',
                template: 'productLoanAmountStep',
                formId: 'productLoanAmountStep',
                schema: Schema.Product.loanAmount,
                data: initialData
                onSubmit: function (data, wizard) {
                    var self = this;
                    var extend = _.extend(wizard.mergedData(), data);

                    console.log(self);
                    console.log(extend);

                        Meteor.call('loan_productUpdate', this.docId, extend, function (error, result) {
                            if (error) {
                                alertify.error(error.message);
                            } else {
                                wizard.clearData();
                                alertify.success('Success');
                            }
                        });
                }
            }
        ];
    }
});
```

1.  Can't get new value of `wizard.mergedData()` (previous step) that I updated, It still the same value of initial data from database.
2. It is Ok  for `data` of the last step
 
Please help me.

**Comment by thearabbit** [comment]
Could you help me?

**Comment by Pagebakers** [comment]
I'll try to have a look tonight, I don't have much free time recently, sorry.

**Comment by thearabbit** [comment]
Thanks for your helping.

**Comment by thearabbit** [comment]
I tried to test `https://github.com/kepler/meteor-autoform-wizard/` forked from this..
work fine for update, but it seem no longer up to date.

**Comment by thearabbit** [comment]
But don't work with custom template (https://github.com/kepler/meteor-autoform-wizard/).
Now I need you help me :100:

**Comment by Pagebakers** [comment]
Can you please put a working example online, so I can reproduce this and come with a solution?

**Comment by thearabbit** [comment]
It's my repo [https://github.com/thearabbit/autoform-wizard-example.git](https://github.com/thearabbit/autoform-wizard-example.git).
Please correct me

1. don't show `autoform label`, but It work fine before
2. update form.

Thanks for your helping.

**Comment by thearabbit** [comment]
Maybe I missing any code, it don't work well.

**Comment by thearabbit** [comment]
Could you help me?

**Comment by Pagebakers** [comment]
Yes, today I finally have some time to drop in!

**Comment by Pagebakers** [comment]
Ok I had a look, there's a lot going on, which is basic Meteor stuff unrelated to the wizard package.
I'll give you a few hints to get it working, but I can't give Meteor suppport here.

1. You forgot to put quotes around the quick field names: `{{> afQuickField name='name'}}`
2. Put your `Schema` in common code, for example in `/both/schema.js`
3. Attach the schema to the collection, the schema is not attached, that's why the insert doesn't work.

Good luck

**Comment by thearabbit** [comment]
Thanks now work fine for `insert`.
But still problem with `update`, It don't get data updated on `step 1` when `submit on last step`.
Now I found the problem, If ...:
1. I tried to change any data on `step 1`
2. Click next to `step 2` (but don't click `submit` immediately). By the `back`, I click `back` to `step 1` again (don't change anything).
3. The final I click next again (last step), and `submit`, It work fine.

**Comment by thearabbit** [comment]
It work, if we click `back` before `submit` on last step.
But we can't get `currentDoc, docId` via `this` to update collection by `id`.
Could you help me again? now I update repo.

**Comment by thearabbit** [comment]
Now I tried in my `example repo` by don't use `data:........ of steps helper`
```js
<!--Wizard Step-->
<template name="staffGeneral">
    {{#autoForm id="staffGeneral" schema=step.schema doc=data}}
        {{> afQuickField name="name"}}
        {{> afQuickField name="gender"}}

        {{> wizardButtons}}
    {{/autoForm}}
</template>

<template name="staffContact">
    {{#autoForm id="staffContact" schema=step.schema doc=data}}

        {{> afQuickField name="telephone"}}
        {{> afQuickField name="address"}}

        {{> wizardButtons}}

    {{/autoForm}}
</template>
--------------------------------------
Template.staffGeneral.helpers({
    data: function () {
        var staffId = FlowRouter.getParam('staffId');
        return Staff.findOne(staffId);
    }
});
Template.staffContact.helpers({
    data: function () {
        var staffId = FlowRouter.getParam('staffId');
        return Staff.findOne(staffId);
    }
});
```
It work fine (can get extend data of the previous step).
But have problem when I click back to the previous step, It don't show value updated on textbox (show init value form database).

**Comment by Pagebakers** [comment]
You have to add the 'collection' to the autoform, otherwise you wont update anything, please read the AutoForm documentation.

**Comment by thearabbit** [comment]
Thanks for your reply.
have to add `collection` to
```js
{{> wizard id="staffUpdate"......
// ------------- or--------------------
`<template name="staffGeneral">
    {{#autoForm id="staffGeneral"..........`
```
But still problem with update, It don't get data updated on step 1 when submit on last step.
Now I found the problem, If ...:
1. I tried to change any data on step 1
2. Click next to step 2 (but don't click submit immediately). By the back, I click back to step 1 again (don't change anything).
3. The final I click next again (last step), and submit, It work fine.
--------------------

**Comment by Pagebakers** [comment]
{{#autoForm id="staffContact" collection="Staff" schema=step.schema doc=data}}

another solution would be to add an onSubmit handler to your staffGeneral step and updating the collection from there.

**Comment by thearabbit** [comment]
I will try soon.
but I should be use `steps helper` or not
```js
insertTpl.helpers({
    steps: function () {
       // Set initial data to update
        var initialData = Loan.Collection.Product.findOne(this._id);

        return [
            {
                id: 'general',
                title: 'General',
                template: 'productGeneralStep',
                formId: 'productGeneralStep',
                schema: Schema.Product.general,
                data: initialData
            },
```

**Comment by thearabbit** [comment]
Oh.., It still don't get data updated on step 1 when submit on last the step (update form).

**Comment by Pagebakers** [comment]
Something like this, so from the bottom of my head
``` javascript
insertTpl.helpers({
    doc: function() { return Staff.findOne(/*id here*/) },
    steps: function () {
       // Set initial data to update
        var initialData = Loan.Collection.Product.findOne(this._id);

        return [
            {
                id: 'general',
                title: 'General',
                template: 'productGeneralStep',
                formId: 'productGeneralStep',
                schema: Schema.Product.general,
                onSubmit: function(data, wizard) {
                     Staff.update(data._id, data);
                     wizard.next(data);
                 }
            },
```

**Comment by thearabbit** [comment]
So we change `doc=step.data` to `doc=doc` (helper).

**Comment by thearabbit** [comment]
Now It work fine for update form, when I separate initial doc by step:
```js
// Update
Template.staffUpdate.helpers({
    steps: function () {
        // Get data for update form
        var staffId = FlowRouter.getParam('staffId');
        var data = Staff.findOne(staffId);
        
        // Separate initial doc by step
        var initDoc = {};
        initDoc.general = {name: data.name, gender: data.gender};
        initDoc.contact = {telephone: data.telephone, address: data.address};
        initDoc.contact2 = {telephone2: data.telephone2, address2: data.address2};

        return [
            {
                id: 'general',
                title: 'General',
                template: 'staffGeneral',
                formId: 'staffGeneral',
                schema: Schemas.general,
                data: initDoc.general
            },
            {
                id: 'contact',
                title: 'Contact',
                template: 'staffContact',
                formId: 'staffContact',
                schema: Schemas.contact,
                data: initDoc.contact
            },
            {
                id: 'contact2',
                title: 'Contact2',
                template: 'staffContact2',
                formId: 'staffContact2',
                schema: Schemas.contact2,
                data: initDoc.contact2,
                onSubmit: function (data, wizard) {
                    var self = this;
                    var extend = _.extend(wizard.mergedData(), data);

                    console.log(self);
                    console.log(extend);
..............
```
`console.log(extend); // work fine for all step`.
`console.log(self);` // don't  get data from AutoForm instance.

Thanks for all your helping :+1: .

**Comment by Pagebakers** [comment]
Cool great!

**Comment by thearabbit** [comment]
But `console.log(self);` don't get data from AutoForm instance such as `docId, currentData...`, it get the data form the last step.

Could I request `data:.........` support `function()`?
```js
.......
data: function(){
  .............
  return {..........};
}
```
