### ISSUE TITLE
pathForStep helper adds step ID but link doesn't do anything

### ISSUE THREAD

**Issue by jykae** [forwarder/meteor-wizard#72]
We tried using pathForStep helper, it adds http://localhost:3000/api/new/simple#base-information step ID to URL but it doesn't link anywhere.

https://github.com/apinf/api-umbrella-dashboard/blob/feature/803-navigation-wizard-header/client/views/api_backends/add-backend-workflow/wizard-bootstrap-steps.html#L5

**Comment by jykae** [comment]
We are using Iron Router, does each step need own route?

**Comment by Pagebakers** [comment]
Please check here https://github.com/forwarder/meteor-wizard#using-routers- to see how to use the wizard with iron router. You should use one route per step, with a :step parameter, as described in the docs.

**Comment by brylie** [comment]
Great documentation! Thanks :+1:

**Comment by jykae** [comment]
@Pagebakers Great, this will help :)

**Comment by Pagebakers** [comment]
Good luck! thanks for using this package!
