### ISSUE TITLE
Iron Router pathFor helper not working as expected when using Wizard route

### ISSUE THREAD

**Issue by brylie** [forwarder/meteor-wizard#73]
We have a wizard route that accepts a parameter for the step id. We are trying to use the Iron Router `pathFor` helper to generate a link to the wizard page, at step 1. How can we generate a link to a wizard page, and display the first step?

**Comment by brylie** [comment]
It turns out that the fix to this question was a bit obscure, but boils down to the step parameter needing to be optional. Our working route looks something like this:

```js
Router.route("/wizard/:step?", function () { // note the question mark indicating optional parameter
  this.render("wizard");
}, {
  name: "wizard"
});
```

We are then able to use the Iron Router `pathFor` template in our navigation menu:

```
...
<a href="{{ pathFor route='wizard' }}">
```

**Comment by Pagebakers** [comment]
Indeed, only options are to hardcode the first step, or use an optional parameter.

I'll add this to the docs, thanks!
