### ISSUE TITLE
wizard.mergedData() return {}

### ISSUE THREAD

**Issue by olexandrbig** [forwarder/meteor-wizard#75]
I have wizard with 6 steps

Part of step settings
`
{
  id: '6',
  title: 'Question 6',
  template: 'questionnaireStepSix',
  formId: 'questionnaire-step-six-form',
  schema: ModuleQuestionnaireSchemaStepSix,
  data:this.getRequirements,
  onSubmit: function (data, wizard) {
	console.log(wizard.mergedData());
  }
}
`
Step template
`
<template name="questionnaireStepSix">
    {{# autoForm id="questionnaire-step-six-form" type="normal"
    docId=this._id
    collection=getModules
    doc=step.data
    schema=step.schema
    }}
        <div class="row">
            <div class="col-md-12">{{> afQuickField name='howDistributed' }}</div>
        </div>
        {{> questionnaireButtons}}
    {{/ autoForm}}
</template>
`
Wizard component
`
{{> wizard id="questionnaire" steps=stepsQuestionnaire nextButton='Next' backButton='Back' confirmButton='Finish' stepsTemplate='questionnaireSteps'}}
`

After all 6 step wizard.mergedData() return empty object, but each step return correct data

**Comment by Pagebakers** [comment]
Do you use custom onSubmit handlers on the previous steps?

**Comment by olexandrbig** [comment]
Yes, like this
`
onSubmit: function (data, wizard) {
        if(data.kindOfSoftware == 'YES'){
          wizard.next();
        }else{
          wizard.show('3');
        }
      }
`

**Comment by Pagebakers** [comment]
Right, it's not very clear in the docs, I'll update them.

You should call wizard.next like `wizard.next(data)` in order to pass the data on.

**Comment by olexandrbig** [comment]
Will it works for wizard.show('3') ? 
like - wizard.show('3',data)

**Comment by Pagebakers** [comment]
Actually you should do

`wizard.setData(/* step id */, data)`

This will make it work with wizard.show too and there's no need to pass the data to next()

**Comment by olexandrbig** [comment]
@Pagebakers  This fix problem, thank you

**Comment by Pagebakers** [comment]
Great!
