### ISSUE TITLE
wizard is not cleared for new order

### ISSUE THREAD

**Issue by slepit** [forwarder/meteor-wizard#76]
Hi,

You wizard is working fine except when placing a new order (after inserting a first one). 
The values in the fields are not cleared after clicking the "place a new order" button. I tried this on your example without any changes. It seems the cache does not get cleared even though the option clearOnDestroy=true is passed to the wizard in the HTML template.

Do you have any clue or idea to fix this ?
.

**Comment by Pagebakers** [comment]
Can't really say anything without some example code.
