### ISSUE TITLE
Wizard undefined

### ISSUE THREAD

**Issue by vmatekole** [forwarder/meteor-wizard#78]
Hi!

When calling Wizard.useRouter I'm getting Wizard undefined, despite me running it within the client/lib on startup. Additionally, I can't see it in the console either. 

Here is my package list, I am using Meteor 1.4:
accounts-base@1.2.11
accounts-password@1.1.13
aldeed:autoform@5.7.1
aldeed:autoform-bs-datepicker@1.1.1
aldeed:autoform-select2@2.0.2
aldeed:collection2@2.5.0
aldeed:simple-schema@1.3.3
aldeed:tabular@1.6.1
aldeed:template-extension@3.4.3
allow-deny@1.0.5
anti:i18n@0.4.3
aslagle:reactive-table@0.8.35
autoupdate@1.2.11
babel-compiler@6.9.1_1
babel-runtime@0.1.11_1
base64@1.0.9
binary-heap@1.0.9
blaze@2.1.9
blaze-html-templates@1.0.5
blaze-tools@1.0.10
boilerplate-generator@1.0.10
bootstrp:tagsinput@0.5.0
caching-compiler@1.1.7_1
caching-html-compiler@1.0.7
callback-hook@1.0.9
check@1.2.3
coffeescript@1.2.4_2
d3@1.0.0
dburles:collection-helpers@1.0.4
ddp@1.2.5
ddp-client@1.2.9
ddp-common@1.2.6
ddp-rate-limiter@1.0.5
ddp-server@1.2.10
deps@1.0.12
diff-sequence@1.0.6
ecmascript@0.5.8_1
ecmascript-runtime@0.3.14_1
ejson@1.0.12
email@1.0.16
es5-shim@4.6.14_1
fastclick@1.0.12
fortawesome:fontawesome@4.6.3
forwarder:autoform-wizard@0.9.1
forwarder:autoform-wizard-iron-router@0.1.4
fourseven:scss@3.10.0
geojson-utils@1.0.9
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.9_1
iain:accounting@0.4.2
id-map@1.0.8
insecure@1.0.7
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.0.13
iron:url@1.0.11
jeremy:selectize@0.12.1_5
jquery@1.11.9
lamatyus:mixitup@2.1.11
launch-screen@1.0.12
lepozepo:s3@5.2.2
less@2.6.5
livedata@1.0.18
localstorage@1.0.11
logging@1.1.15_1
matb33:collection-hooks@0.7.15
meteor@1.2.17_1
meteor-base@1.0.4
meteor-platform@1.2.6
meteorhacks:inject-initial@1.0.4
michalvalasek:autoform-bootstrap-colorpicker@0.1.0
mikael:device@0.0.1
minifier-css@1.2.14_1
minifier-js@1.2.14_1
minimongo@1.0.17
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.7.6_1
modules-runtime@0.7.6_1
momentjs:moment@2.15.1
mongo@1.1.12_1
mongo-id@1.0.5
mrgalaxy:stripe@2.2.2
mrt:jquery-ui@1.9.2
mrt:later@1.6.1
mrt:vimeo@0.1.2
nicolaslopezj:options@1.0.1
nicolaslopezj:reactive-templates@1.2.1
nicolaslopezj:roles@2.4.0
nicolaslopezj:router-layer@0.0.11
npm-bcrypt@0.8.6_3
npm-mongo@1.5.50
numtel:template-from-string@0.1.0
observe-sequence@1.0.12
okgrow:router-autoscroll@0.1.8
ordered-dict@1.0.8
orionjs:accounts@1.8.1
orionjs:attributes@1.8.0
orionjs:base@1.8.0
orionjs:bootstrap@1.8.0
orionjs:collections@1.8.0
orionjs:config@1.8.0
orionjs:core@1.8.0
orionjs:dictionary@1.8.0
orionjs:file-attribute@1.8.0
orionjs:filesystem@1.8.0
orionjs:lang-en@1.8.0
orionjs:relationships@1.8.0
orionjs:s3@1.8.0
orionjs:summernote@1.8.0
pcel:loading@1.0.3
promise@0.8.7
rajit:bootstrap3-datepicker@1.5.1
random@1.0.10
rate-limit@1.0.5
rcy:nouislider@7.0.7_2
reactive-dict@1.1.8
reactive-var@1.0.10
reload@1.1.10
retry@1.0.8
reywood:publish-composite@1.4.2
routepolicy@1.0.11
service-configuration@1.0.10
session@1.1.6
sha@1.0.8
shell-server@0.2.1
softwarerero:accounts-t9n@1.3.3
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.9
standard-minifier-css@1.2.1
standard-minifier-js@1.2.0_1
standard-minifiers@1.0.6
summernote:standalone@0.6.16
templating@1.2.15
templating-compiler@1.2.15
templating-runtime@1.2.15
templating-tools@1.0.5
tracker@1.1.0
twbs:bootstrap@3.3.6
ui@1.0.12
underscore@1.0.9
underscorestring:underscore.string@3.3.4
url@1.0.10
useraccounts:bootstrap@1.12.4
useraccounts:core@1.14.2
useraccounts:iron-routing@1.14.2
valedaemon:circular-progress@1.0.0
vmatekole:country-codes@0.1.1
vmatekole:image-attribute@1.8.0
vmatekole:orion-tags@0.0.1
vmatekole:std-client-libs@0.0.1
vsivsi:job-collection@1.4.0
webapp@1.3.11_1
webapp-hashing@1.0.9
xkmo:youtube-iframe-player@0.4.17
zuuk:stale-session@1.0.8

**Comment by Pagebakers** [comment]
I haven't tested this with 1.4 yet, it might be incompatible. Feel free to send a PR :)
