### ISSUE TITLE
CacheStore.clear not working because of "this"

### ISSUE THREAD

**Issue by christianvoigt** [forwarder/meteor-wizard#8]
Hi, you forgot to use "self" instead of "this" in: https://github.com/forwarder/meteor-wizard/blob/master/cache.js#L42

**Comment by dmitry-sher** [comment]
+1
clear bug, needs to be fixed...

**Comment by Pagebakers** [comment]
Thanks for the report, released 0.4.3.

Sorry for the late fix, I'm still not receiving any Github notifications.

**Comment by christianvoigt** [comment]
Hi, finally found the time to test it. There is another bug in the same loop:
https://github.com/forwarder/meteor-wizard/blob/master/cache.js#L41

the each handler currently has `key` as the first argument, but it has to be the second like this:
```javascript
    _.each(this.keys, function(value, key) {
      Session.set(this.prefix(key), null);
    });
```

By the way, have you seen my pull request? I added FlowRouter support to the wizard.

**Comment by Pagebakers** [comment]
Thanks, I haven't seen the PR yet. I'll check it out right away!
