### ISSUE TITLE
Setting to remove steps <ol>?

### ISSUE THREAD

**Issue by jfraboni** [forwarder/meteor-wizard#81]
@Pagebakers Is there a setting to remove the `<ol>` rendered at the top of each step?  I think you're calling these breadcrumbs.

The following markup is rendered:

```
  <div class="steps">
    <ol>
      <li class="active">
        Step One
      </li>
      <li class="">
        Step Two
      </li>
    </ol>
  </div>
```

But, if your form has many many steps, this gets to be a little much.  What if you don't want this in the UX?  Also, the `active` class does nothing, even with Bootstrap installed.

Finally, if you set the wizard form with `backButton=false`, the breadcrumb feature allows the user to go back anyway.  And when clicking on one of these breadcrumbs, the following error is thrown:

```
Exception in template helper: TypeError: Cannot read property 'defs' of undefined
    at Object.afQuickFieldIsGroup (http://localhost:3000/packages/aldeed_autoform.js?hash=f9d363ae5150353ec5242d140024e66ddde156e7:7059:49)
```

**Comment by Pagebakers** [comment]
You can overwrite the breadcrumbs by configuring:
`stepsTemplate: Optional. A custom steps template.`

Can't say much about that error unfortunately without a reproduction demo.

**Comment by jfraboni** [comment]
Appreciate you @Pagebakers
